"""initial schema

Revision ID: 0b04934b8d3a
Revises: 
Create Date: 2026-04-26 12:54:36.521444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0b04934b8d3a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('google_health_user_id', sa.String(length=128), nullable=False),
    sa.Column('data_type', sa.String(length=64), nullable=False),
    sa.Column('operation', sa.Enum('UPSERT', 'DELETE', name='notification_operation'), nullable=False),
    sa.Column('interval_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('interval_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_queue_google_health_user_id'), 'notification_queue', ['google_health_user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('admin', 'researcher', name='user_role'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('wearable_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('studies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('wearable_type_id', sa.Integer(), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['wearable_type_id'], ['wearable_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_id', sa.Integer(), nullable=False),
    sa.Column('wearable_type_id', sa.Integer(), nullable=False),
    sa.Column('entry_code', sa.String(length=5), nullable=False),
    sa.Column('status', sa.Enum('pending', 'registered', 'revoked', name='participant_status'), nullable=False),
    sa.Column('google_health_user_id', sa.String(length=128), nullable=True),
    sa.Column('oauth_access_token', sa.Text(), nullable=True),
    sa.Column('oauth_refresh_token', sa.Text(), nullable=True),
    sa.Column('oauth_scopes', sa.Text(), nullable=True),
    sa.Column('oauth_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], ),
    sa.ForeignKeyConstraint(['wearable_type_id'], ['wearable_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_participants_entry_code'), 'participants', ['entry_code'], unique=True)
    op.create_index(op.f('ix_participants_google_health_user_id'), 'participants', ['google_health_user_id'], unique=False)
    op.create_index(op.f('ix_participants_study_id'), 'participants', ['study_id'], unique=False)
    op.create_table('study_members',
    sa.Column('study_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('study_id', 'user_id')
    )
    op.create_table('daily_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('source', sa.Enum('fitbit', 'garmin', name='data_source'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('participant_id', 'date', 'source', name='uq_daily_data_participant_date_source')
    )
    op.create_index(op.f('ix_daily_data_participant_id'), 'daily_data', ['participant_id'], unique=False)
    op.create_table('oauth_state',
    sa.Column('state', sa.String(length=128), nullable=False),
    sa.Column('code_verifier', sa.String(length=128), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.PrimaryKeyConstraint('state')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('oauth_state')
    op.drop_index(op.f('ix_daily_data_participant_id'), table_name='daily_data')
    op.drop_table('daily_data')
    op.drop_table('study_members')
    op.drop_index(op.f('ix_participants_study_id'), table_name='participants')
    op.drop_index(op.f('ix_participants_google_health_user_id'), table_name='participants')
    op.drop_index(op.f('ix_participants_entry_code'), table_name='participants')
    op.drop_table('participants')
    op.drop_table('studies')
    op.drop_table('wearable_types')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_notification_queue_google_health_user_id'), table_name='notification_queue')
    op.drop_table('notification_queue')
    # ### end Alembic commands ###
