"""studies: per-PI google oauth client + fernet encryption

Revision ID: 6efa85cd7de2
Revises: 0b04934b8d3a
Create Date: 2026-04-26 13:37:49.932674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.services.crypto import EncryptedText


# revision identifiers, used by Alembic.
revision: str = '6efa85cd7de2'
down_revision: Union[str, None] = '0b04934b8d3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('studies', sa.Column('google_oauth_client_id', sa.Text(), nullable=True))
    op.add_column('studies', sa.Column('google_oauth_client_secret', EncryptedText(), nullable=True))
    op.add_column('studies', sa.Column('google_cloud_project_id', sa.Text(), nullable=True))
    op.add_column('studies', sa.Column('webhook_authorization_value', EncryptedText(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('studies', 'webhook_authorization_value')
    op.drop_column('studies', 'google_cloud_project_id')
    op.drop_column('studies', 'google_oauth_client_secret')
    op.drop_column('studies', 'google_oauth_client_id')
    # ### end Alembic commands ###
